import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import ProgressBar from "@/components/ProgressBar";
import { serif } from "@/lib/fonts";
import { ViewTransitions } from "next-view-transitions";
import "@/styles/globals.css";
import Head from "next/head";
export const metadata: Metadata = {
  title: "He's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@callmebill/lxgw-wenkai-web@latest/style.css" />
      </Head>
      <body>
        <ViewTransitions>
          <ThemeProvider attribute="class" disableTransitionOnChange={false}>
            <div className="max-w-[50rem]  px-4 sm:px-6 md:px-8 mx-auto mt-8 mb-6 relative z-1">
              <ProgressBar />
              <Header />
              {children}
            </div>
          </ThemeProvider>
        </ViewTransitions>
      </body>
    </html>
  );
}
