import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "He's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" disableTransitionOnChange={false}>
          <div className="mx-auto px-4 lg:px-0 lg:mb-0  lg:w-full lg:max-w-3xl  pb-16">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
